# Generated by Django 2.1 on 2018-09-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('tagable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Tagable')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=('tags.tagable',),
        ),
        migrations.CreateModel(
            name='MessagePosted',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Action')),
                ('content', models.TextField(blank=True, max_length=2048)),
                ('last_edited', models.DateTimeField(null=True, verbose_name='Dernière édition')),
            ],
            bases=('tags.action',),
        ),
        migrations.CreateModel(
            name='StateChanged',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Action')),
                ('state', models.CharField(choices=[('opened', 'En cours'), ('closed', 'Close')], max_length=50)),
            ],
            bases=('tags.action',),
        ),
    ]
